# <center> Numpy Basics </center>

In [ ]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

a_array=np.array([1,2,3])

In [ ]:
# print output
print(a_array)


[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [ ]:
#define a,b,c and d as instructed above

a =np.array([10])
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d

print(a)
print(b)
print(c)

print(d)

[10]
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d

shape_a=a.shape
print(shape_a)
shape_b=b.shape
print(shape_b)
shape_c=c.shape
print(shape_c)
shape_d=d.shape
print(shape_d)




(1,)
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
shape_a=a.dtype
print(shape_a)




int64


In [ ]:
# Lets check length of array b, using len() function
# len(b)

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [ ]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)



In [ ]:

new=l3*l4
print(new)


[ 400 1000 1800]


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [ ]:
#Create a numpy array using arange with 1 and 11 as parameter in it


a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [ ]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
a=np.arange(1,11,2)
print(a)



[1 3 5 7 9]


In [ ]:
# create numpy array using eye function with 3 as passed parameter




In [ ]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x=np.arange(1,17)
print(x)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# Reshape x with 2 rows and 8 columns

x.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [ ]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:

x.reshape(2,4,2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [ ]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,18,2)
print (a)


[ 2  4  6  8 10 12 14 16]


In [ ]:
# Get third element in array a
a[2]

6

In [ ]:
#Print 3rd, 5th, and 7th element in array a

print(a[2])
print(a[4])
print(a[6])


6
10
14


Lets check the same for 2 D array

In [ ]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# print the 3rd element from the 3rd row of a

a[2,2]

9

Well done!

Now lets check indexing for 3 D array

In [ ]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b =np.array([[[1,2,3],[4,5,6]],[[7, 8, 9], [10, 11, 12]]])



In [ ]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

element = b[0][1][2]
print(element)


6


In [ ]:
# Create 1D array

arr=np.array([1,2,3,4,5,6,7,8,9,10])




In [ ]:
# Slice elements from 1st to 5th element from the following array:

arr[0:5]



array([1, 2, 3, 4, 5])

Note: The result includes the start index, but excludes the end index.



In [ ]:
# Slice elements from index 5 to the end of the array:
arr[5:]



array([ 6,  7,  8,  9, 10])

In [ ]:
# Slice elements from the beginning to index 5 (not included):

arr[:5]



array([1, 2, 3, 4, 5])

**STEP**

Use the step value to determine the step of the slicing:

In [ ]:
# Print every other element from index 1 to index 7:

print(arr[1:7:2])



[2 4 6]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [ ]:
# Return every other element from the entire array arr:


result = arr[::2]
print(result)

[1 3 5 7 9]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [8]:
##join arr1 and arr2 along columns using concatenate() function

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
result_axis0 = np.concatenate((arr1, arr2), axis=0)
print("Concatenation along axis 0 (rows):\n", result_axis0)

# Concatenate along axis 1 (columns)
result_axis1 = np.concatenate((arr1, arr2), axis=1)
print("Concatenation along axis 1 (columns):\n", result_axis1)



Concatenation along axis 0 (rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenation along axis 1 (columns):
 [[1 2 5 6]
 [3 4 7 8]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [9]:
# append arr2 to arr1

# Append arr2 to arr1 along axis 0 (rows)
result = np.append(arr1, arr2, axis=0)
print("Appending arr2 to arr1 along axis 0:\n", result)

# If you want to append along axis 1 (columns), ensure shapes are compatible
result_axis1 = np.append(arr1, arr2, axis=1)
print("\nAppending arr2 to arr1 along axis 1:\n", result_axis1)

Appending arr2 to arr1 along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Appending arr2 to arr1 along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


Lets use insert() function which Inserts values into array before specified index value

In [14]:
# Inserts values into array x1 before index 4 with elements of x4

# Define the arrays
x1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x4 = np.array([10, 20, 30])

# Insert values from x4 into x1 before index 4
x2= np.insert(x1, 4, x4)

# Print the result
print("Array x2 after insertion:\n", x2)


Array x2 after insertion:
 [ 1  2  3  4 10 20 30  5  6  7  8  9 10]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [15]:
# delete 2nd element from array x2

result1 = np.delete(x2, 1)


# Print the result
print("Array after deleting the 2nd element:\n", result1)

Array after deleting the 2nd element:
 [ 1  3  4 10 20 30  5  6  7  8  9 10]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!